version: '3.8'

services:
  cardgame-api:
    image: cardgame-api:latest
    container_name: cardgame-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
      - LOG_LEVEL=INFO
      - PORT=8080
      - METRICS_ENABLED=true
      - OTEL_SERVICE_NAME=cardgame-api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/hello"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:exec,nosuid,nodev,size=100m
    user: "65532:65532"
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE