version: '3.8'

services:
  cardgame-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: cardgame-api:latest
    container_name: cardgame-api
    ports:
      - "8080:8080"
    environment:
      # Application settings
      - PORT=8080
      - GIN_MODE=release
      - LOG_LEVEL=INFO
      
      # For development, you might want DEBUG logging
      # - LOG_LEVEL=DEBUG
      # - GIN_MODE=debug
      
      # Trusted proxies configuration (adjust for your environment)
      # - TRUSTED_PROXIES=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
    
    # Health check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/hello"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    
    # Restart policy
    restart: unless-stopped
    
    # Logging configuration
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    
    # Network
    networks:
      - cardgame-net

  # Optional: Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: cardgame-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    networks:
      - cardgame-net
    restart: unless-stopped
    profiles:
      - monitoring

  # Optional: Grafana for metrics visualization
  grafana:
    image: grafana/grafana:latest
    container_name: cardgame-grafana
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    networks:
      - cardgame-net
    restart: unless-stopped
    depends_on:
      - prometheus
    profiles:
      - monitoring

networks:
  cardgame-net:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data: