version: '3.8'

# Docker Compose with secrets management
services:
  cardgame-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: cardgame-api:latest
    container_name: cardgame-api
    ports:
      - "8080:8080"
    
    # Environment variables from .env file
    env_file:
      - .env
    
    # Secrets (for sensitive data)
    secrets:
      - api_key
      - db_password
      - jwt_secret
    
    # Environment variables referencing secrets
    environment:
      - PORT=8080
      - GIN_MODE=${GIN_MODE:-release}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - TRUSTED_PROXIES=${TRUSTED_PROXIES:-}
      # Reference secrets via /run/secrets/
      - API_KEY_FILE=/run/secrets/api_key
      - DB_PASSWORD_FILE=/run/secrets/db_password
      - JWT_SECRET_FILE=/run/secrets/jwt_secret
    
    # Security options
    security_opt:
      - no-new-privileges:true
    
    # Read-only root filesystem
    read_only: true
    
    # Temporary filesystems
    tmpfs:
      - /tmp
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/hello"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    
    restart: unless-stopped
    
    networks:
      - cardgame-net

# Secrets definitions
secrets:
  api_key:
    file: ./secrets/api_key.txt
  db_password:
    file: ./secrets/db_password.txt
  jwt_secret:
    file: ./secrets/jwt_secret.txt

networks:
  cardgame-net:
    driver: bridge